export const INIT_PRODUCTS_LIST = 'INIT_PRODUCTS_LIST';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const INIT_CURRENT_PRODUCT_CARD = 'INIT_CURRENT_PRODUCT_CARD';
export const UPDATE_PRODUCT_IN_STOK = 'UPDATE_PRODUCT_IN_STOK';
export const FILTER_PRODUCTS_LIST = 'FILTER_PRODUCTS_LIST';
export const SORT_PRODUCTS_LIST = 'SORT_PRODUCTS_LIST';
export const RETURN_PRODUCT_IN_STOK = 'RETURN_PRODUCT_IN_STOK';
export const CHANGE_PRODUCT_STATUS = 'CHANGE_PRODUCT_STATUS';
export const RETURN_ORDER_IN_STOK = 'RETURN_ORDER_IN_STOK';

